### ISSUE TITLE
slow with large data

### ISSUE THREAD

**Issue by AaronGullickson** [paulfitz/daff#53]
Hi, I was very excited to see this program as I work on a collaborative data project where merging in changes provided by different members has become very difficult and tricky. I was able to get it up and running with python on linux and it worked great for the example you provide on the site. However when I tried changing just one cell in my own dataset which is very large (117K rows), it took over five hours to complete the merge. I am wondering if this is expected behavior for such a large dataset or if there might be some way to speed this up. 

Thanks.

**Comment by paulfitz** [comment]
That is slower than I'd have expected. Just tried a diff on a random 150k row x 45 column table and it took 5 secs in javascript, 18 secs in python.  There may be something daft in the merge logic then, I haven't been testing that on larger datasets  Will poke at it, thanks for reporting.  Should be fixable since the merging is in principle the easy part once the diffs are done :-)

If you happen to have a test set you can pass along, I'd appreciate it - though understood if it is private. My email address is on my github profile.

**Comment by paulfitz** [comment]
Hi @AaronGullickson, I'm not seeing anything like the times you quoted on merges of large random tables. How many columns do you have? Are the rows easy to distinguish with some unique identifier or are there many repeats? What format is your data stored in?  I'd be grateful for anything you can tell me, it will help come up with a comparable testcase.

**Comment by AaronGullickson** [comment]
Hi thanks for getting back to me. There are 21 columns so even smaller than your test cases. My guess is that maybe there is an encoding issue or end of line issue or something that daff is having trouble with but I am not sure. I will send you the data that is causing the problem privately. Hopefully that will help.

**Comment by rversteegen** [comment]
Hi, very nice tool, but the very first csv file I tried it out on took 28 seconds to run :/
It appears to be spending all that time concatenating strings together, which takes quadratic time. I realise you wrote it in haxe, but I can only say out that you must concatenate a list of strings using ''.join(strings) in python, not sum(strings, '').
I'm using daff 1.3.24 in python 2.7 installed from pip.
Here are the files I tried:
[items.tar.gz](https://github.com/paulfitz/daff/files/1608279/items.tar.gz)

**Comment by paulfitz** [comment]
@rversteegen thanks for the test case.  I see a factor of 5 in time taken for your test case depending on whether output is colorized (`--color`) or not (`--no-color`).

```
$ time daff.py --no-color items.csv items_new.csv > /dev/null
real	0m1.124s
user	0m1.058s
sys	0m0.048s
$ time daff.py --color items.csv items_new.csv > /dev/null
real	0m5.461s
user	0m3.394s
sys	0m2.060s
```
So looks like the color stuff must be inefficient for many columns.  Thanks for reporting.

**Comment by rversteegen** [comment]
It only took 5.5s on your machine, and 27.5s on mine? That's very strange; are there other optimisations since 1.3.24 was released?
Hmmm, I think maybe the huge time difference is due to glibc using a routine (probably __memcpy_ssse3 according to gdb) which is very slow on my AMD Bulldozer CPU. I've had this sort of glibc problem before (can't remember whether it was memcpy or some other basic function), although I couldn't find any mention of a __memcpy_ssse3 problem with a web search. I really ought to investigate and get in contact with the glibc devs.

--no-color ran in 3.2s for me, so over 8 times faster.
I also notice a very large fraction of the --color time is spent in system calls. Why is that? That would seem to hint at why printing in colour is so slow.
Although, 1.1 seconds for producing a diff seems to imply that something in daff is still quadratic time, and that's still slow enough to be problem if git is set up to call daff.

**Comment by rversteegen** [comment]
Oh and also, thanks for working on this so quickly!

**Comment by paulfitz** [comment]
No particular optimizations. I included some changes in outputting based on your case in version 1.3.26.  I'd be interested in whether you see any improvement with that.

In general, your data is tough for daff.  There's a lot of repeated, similar cells.  Daff is optimized for cases where there are some columns that can be put together as an approximate private key.  It goes looking for such columns, and the less distinctiveness there is the slower things will be.

**Comment by rversteegen** [comment]
Sorry, I didn't realise you had released this improvement in a new version (I misread what you wrote). I was putting off installing haxe and figuring out how to run daff.

On my machine --color now runs in 5.8s (down from 27s) and --no-color in 3.2s (no change).
Also, I was wrong about there being a problem in glibc -- I profiled and found only 15% of the time was spent in memcpy. The runtime was spread around a number of different python functions. (So I have no idea why it was so much slower on my machine)

Yes, I can see that these csv files really are pathlogical, and fairly large too. It seems too much to ask that they be processed any faster. Thanks for the fix.

**Comment by paulfitz** [comment]
Closing this.  It is now also practical to diff much larger tables with daff via its sqlite support, see discussion in #127
